In [26]:
# DO NOT MODIFY

# import appropriate libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier

In [3]:
# DO NOT MODIFY

# we will use the daily weather dataset of this exercise.

def get_data():
    return pd.read_csv('/Users/Jacqueline/Documents/PythonForDataScience/Week-7-MachineLearning/weather/daily_weather.csv')

df = get_data()

In [8]:
# modify this cell

def detect_nulls(matx):
    ### BEGIN SOLUTION
    if matx.isnull().values.any()== True:
        return True
    else:
        return False
    ### END SOLUTION

In [9]:

# DO NOT MODIFY
ans = True

try: assert np.alltrue(detect_nulls(df) == ans)
except AssertionError as e: print("Try again, your output did not match the expected answer above")

In [10]:
# modify this cell

def clean_data(matx):
    ### BEGIN SOLUTION
    cleaned = matx.dropna()
    return cleaned

    ### END SOLUTION

In [11]:

# DO NOT MODIFY

try: 
    df2=clean_data(df)
    assert np.alltrue(df2.shape[0] == 1064)
except AssertionError as e: print("Try again")

In [12]:

df2.describe()

,number,air_pressure_9am,air_temp_9am,avg_wind_direction_9am,avg_wind_speed_9am,max_wind_direction_9am,max_wind_speed_9am,rain_accumulation_9am,rain_duration_9am,relative_humidity_9am,relative_humidity_3pm
count,1064.000000,1064.000000,1064.000000,1064.000000,1064.000000,1064.000000,1064.000000,1064.000000,1064.000000,1064.000000,1064.000000
mean,545.001880,918.903180,65.022609,142.306756,5.485793,148.480424,6.999714,0.182023,266.393697,34.077440,35.148381
std,316.796111,3.179040,11.168033,69.149472,4.534427,67.154911,5.590790,1.534493,1503.092216,25.356668,22.365475
min,0.000000,907.990000,36.752000,15.500000,0.693451,28.900000,1.185578,0.000000,0.000000,6.090000,5.300000
25%,269.750000,916.595376,57.398000,65.979244,2.245529,76.335351,3.064608,0.000000,0.000000,15.093365,17.360468
50%,543.500000,918.942281,65.778479,165.937461,3.869906,176.350000,4.943637,0.000000,0.000000,23.135000,24.371286
75%,819.250000,921.169054,73.530872,191.100000,7.264463,201.125000,8.747888,0.000000,0.000000,44.660000,51.922500
max,1094.000000,929.320000,98.906000,343.400000,23.554978,312.200000,29.840780,24.020000,17704.000000,92.620000,92.250000

In [19]:
# modify this cell

def classification_task(df, C, X):
    ### BEGIN SOLUTION
    clean_data = df.copy()
    clean_data["target"] = (clean_data[C]>X)*1
    return clean_data

    ### END SOLUTION

In [20]:
# DO NOT MODIFY

ans = 558

try: 
    c = classification_task(df2, 'air_temp_9am', 65.0)
    assert np.alltrue(c['target'].sum() == ans)
except AssertionError as e: print("Try again, your solution did not produce the expected output above")

In [31]:
c.head()

,air_pressure_9am,air_temp_9am,avg_wind_direction_9am,avg_wind_speed_9am,max_wind_direction_9am,max_wind_speed_9am,rain_accumulation_9am,rain_duration_9am,relative_humidity_9am,relative_humidity_3pm,target
0,918.060000,74.822000,271.100000,2.080354,295.400000,2.863283,0.0,0.0,42.420000,36.160000,1
1,917.347688,71.403843,101.935179,2.443009,140.471548,3.533324,0.0,0.0,24.328697,19.426597,1
2,923.040000,60.638000,51.000000,17.067852,63.700000,22.100967,0.0,20.0,8.900000,14.460000,0
3,920.502751,70.138895,198.832133,4.337363,211.203341,5.190045,0.0,0.0,12.189102,12.742547,1
4,921.160000,44.294000,277.800000,1.856660,136.500000,2.863283,8.9,14730.0,92.410000,76.740000,0

In [21]:
del c['number']

In [32]:
def get_ready(df):
    from sklearn.model_selection import train_test_split
    # declare features to use
    features = ['air_pressure_9am','avg_wind_direction_9am','avg_wind_speed_9am','max_wind_direction_9am']
    # create copy
    df_copy = df.copy()
    df_copy['target'] = (df_copy['air_temp_9am'] > 65.0)*1
    # separate features from target
    X=df_copy[features]
    y=df_copy['target']
    # perform split and return
    return train_test_split(X, y, test_size=0.33, random_state=983)

In [33]:

X_train, X_test, y_train, y_test = get_ready(pd.read_csv('/Users/Jacqueline/Documents/PythonForDataScience/Week-7-MachineLearning/weather/daily_weather.csv').dropna())

In [67]:

# modify this cell

def train_classifier(X_train, y_train):
    ### BEGIN SOLUTION
    classifier = DecisionTreeClassifier(max_leaf_nodes=4, random_state=0)
    x = classifier.fit(X_train, y_train)
    return x

    ### END SOLUTION

In [68]:

# DO NOT MODIFY

min_score = 0.63

try: 
    v = train_classifier(X_train, y_train)
    y_pred = v.predict(X_test)
    assert np.alltrue(accuracy_score(y_test, y_pred) > min_score)
except AssertionError as e: print("Keep trying - can you get an accuracy_score > %f" % min_score)

In [69]:
accuracy_score(y_test, y_pred)

0.6477272727272727